FROM clojure:temurin-21-tools-deps-alpine

WORKDIR /app

# Copy deps first for caching
COPY deps.edn .
RUN clojure -P

# Copy source
COPY src src
COPY resources resources

EXPOSE 3001

CMD ["clojure", "-M:run"]

